"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 2000

[aws]
disabled = true
# format = 'on [$symbol$profile]($style) '
# style = 'bold blue'
# symbol = 'ğŸ…° '
# [aws.profile_aliases]
# default = 'Foo'

[directory]
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch]($style) "

[nodejs]
disabled = true

[line_break]
disabled = false

[time]
disabled = false
format = 'ğŸ•™[ $time ]($style)'
time_format = "%R"

[git_status]
ahead = "â‡¡${count}"
behind = "â‡£${count}"
conflicted = "[ğŸ¤ª${count}](bright-red) "
deleted = "[ğŸ—‘${count}](red) "
disabled = true
diverged = "â‡¡${ahead_count} â‡£${behind_count}"
modified = "[ğŸ“’${count}](yellow) "
renamed = "[ğŸš—${count}](bright-red) "
staged = "[âœ”${count}](green) "
stashed = "[ï¿½ ${count}](bright-blue) "
untracked = "ğŸ¤·â€${count} "

[git_commit]
only_detached = false

[java]
disabled = true

[package]
disabled = true
